{{ if .Values.service.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "odk.fullname" . }}-service-transfer
spec:
  accessModes:
    - {{ .Values.service.persistence.accessMode | quote }}
  volumeMode: Filesystem
  storageClassName: {{ .Values.service.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.service.persistence.size }}
{{ end }}