apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "odk.fullname" . }}-service
    version: "1.0"
  name: {{ include "odk.fullname" . }}-service
spec:
  ports:
  - port: 8383
    protocol: TCP
    targetPort: 8383
  selector:
    app: {{ include "odk.fullname" . }}-service
