{{ if .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "odk.fullname" . }}-enketo-redis-main-data
spec:
  accessModes:
    - {{ .Values.redis.persistence.accessMode }}
  volumeMode: Filesystem
  storageClassName: {{ .Values.redis.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{ end }}      