apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "odk.fullname" . }}-enketo
    version: "{{ .Values.image.tag | default .Chart.AppVersion }}"
  name: {{ include "odk.fullname" . }}-enketo
spec:
  ports:
  - port: 8005
    protocol: TCP
    targetPort: 8005
  selector:
    app: {{ include "odk.fullname" . }}-enketo
    