{{ if .Values.postfix.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "odk.fullname" . }}-postfix
  name: {{ include "odk.fullname" . }}-postfix
spec:
  ports:
  - port: 25
    protocol: TCP
    targetPort: 25
  selector:
    app: {{ include "odk.fullname" . }}-postfix
{{ end }}